name: Build RacciCore

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[SKIP]')"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK-17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup build cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/jdks
            ~/.gradle/native
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
        #-Pversion=${version} --stacktrace

      - name: Upload artififacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: LibraryCatalog
          path: build/version-catalog/*.toml

      - name: Publish
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew publish
